### ISSUE TITLE
ExperimentHub error + Full single-cell dataset from Jackson et al. (2020)

### ISSUE THREAD

**Issue by lassedochreden** [BodenmillerGroup/imcdatasets#21]
Hi @ndamond, 

Two things: 
1. I get following error installing `imcdatasets` via BioC: `error: ‘DamondPancreas2019_sce’ not found in ExperimentHub`.

2. I was wondering whether it would be nicer to have the option to read in the **full** dataset from _Jackson et al. (2020)_ as a `sce` object rather than the subset. At least for the single-cell expression data (not necessarily for the images). 

Thanks for looking into it! 

Short SessionInfo: 
`R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS`

**Comment by ndamond** [comment]
Hi @lassedochreden,

Thanks for trying out `imcdatasets`.

1. Which BioC version are you using? Could you update to 3.16?

2. The original idea was to provide complete datasets with single cell data + images + masks. It was not feasible to have full datasets due to the memory space required to store image data. But separately providing full single cell data should work and makes sense, I'll look into it.
Great suggestion, thank you!

**Comment by lassedochreden** [comment]
Hi @ndamond, 

I was using `3.15` - Works with `3.16`, thanks! 

Would still be great to have a **full single-cell data option**. Thanks in advance!

**Comment by ndamond** [comment]
Hi @lassedochreden,

I just looked into it and providing full single cell data (and all cell masks) seems doable.
Will work on it (https://github.com/BodenmillerGroup/imcdatasets/pull/23) and let you know how it goes.

**Comment by ndamond** [comment]
Done with #23 (requires Bioconductor 3.17)
